### ISSUE TITLE
wrong path to python

### ISSUE THREAD

**Issue by sdementen** [brettcannon/python-azure-web-app-cookiecutter#5]
When using python 3.5.3 extension, the cookiecutter generates the path D:\home\python353\python.exe but the path to be used is D:\home\python35\python.exe.
This may have changed recently...

**Comment by brettcannon** [comment]
I just got back from vacation but I will try to have a look at this next week.

**Comment by brettcannon** [comment]
Should be all fixed now. It turns out Jinja  2.9 made a change which broke the templating used to calculate the version number for paths.
